AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 102625093955

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Olaf Conijn
      AccountId: '102625093955'
      RootEmail: olaf_conijn@hotmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
        - !Ref RestrictUnusedRegionsSCP

  AccountBAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account B
      AccountId: '362239514602'
      RootEmail: account+b@olafconijn.awsapps.com

  AccountAAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account A
      AccountId: '340381375986'
      RootEmail: account+a@olafconijn.awsapps.com
      Alias: b340381375986
      PasswordPolicy: !Ref PasswordPolicy

  UsersAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Users Account
      AccountId: '549476213961'
      RootEmail: account+users@olafconijn.awsapps.com

  AccountCAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Account C
      AccountId: '673026687213'
      RootEmail: account+c@olafconijn.awsapps.com

  Test18SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test18
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test5SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test5
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test11SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test11
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test17SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test17
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  TestSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test
      Description: xxxx
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'app-integrations:CreateEventIntegration'
            Resource:
              - '*'

  Test16SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test16
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'

  Test13SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test13
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
              - 'budgets:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-west-1
                  - eu-west-1
                  - us-east-1
                  - eu-central-1

  ProtectCommunityRPsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: ProtectCommunityRPs
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenySetPublicAccessBlock
            Effect: Deny
            Action: 's3:PutAccountPublicAccessBlock'
            Resource: '*'

  Test19SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test19
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test15SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test15
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test6SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test6
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test22SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test22
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test8SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test8
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test12SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test12
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test21SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test21
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test9SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test9
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test4SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test4
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test3SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test3
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test2SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test2
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test7SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test7
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test20SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test20
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test14SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test14
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  Test10SCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: test10
      Description: ''
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Statement1
            Effect: Deny
            Action:
              - 'aps:CreateWorkspace'
            Resource:
              - '*'

  PasswordPolicy:
    Type: OC::ORG::PasswordPolicy
    Properties:
      # MaxPasswordAge: 30
      MinimumPasswordLength: 8
      RequireLowercaseCharacters: true
      # RequireNumbers: true
      # RequireSymbols: true
      # RequireUppercaseCharacters: true
      PasswordReusePrevention: 3
      # AllowUsersToChangePassword: true