AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  assumeRolePrincipal:
    Type: String

Resources:
  OrganizationFormationBuildAccessRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess # see: https://github.com/org-formation/org-formation-cli/blob/master/docs/least-priviledge.md
      RoleName: XXX-OrganizationFormationBuildAccessRole
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
         - Effect: Allow
           Action: sts:AssumeRole
           Principal:
            AWS: !Ref assumeRolePrincipal